# Generated by Django 5.0.6 on 2024-07-15 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_pedido_estado_pago_alter_pedido_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('enviado', 'Enviado'), ('preparado', 'Preparado'), ('entregado', 'Entregado')], default='pendiente', max_length=10),
        ),
    ]
